### PR TITLE
Created index w/ old anchor-link code

### PR DESCRIPTION
**Pull request by jimmythongtran**
I found old code from my Udacity Intro to Programming course. I haven't studied it yet but I recommend checking it out. Feel free to hack away at it and reorganize it and bake in the mahjong.txt into your newly hacked version.

### CODE REVIEW

**Comment by jimmythongtran** [comment]
Oh never mind, it did update. Whew!

**Comment by stephenhoang1** [comment]
There's a conflict here which I can't resolve, so i can't merge it to the master branch. It probably best that you go back and take a look at what you put in, or abandon it altogether.

**Comment by stephenhoang1** [comment]
ok, i've resolved the conflict

**Comment by stephenhoang1** [comment]
merging

**Pull request merged**
